mainSections = ["medical", "tech", "galgame", "thoughts", "game"]
enableHomePosts = true
rssFullContent = true
SortBy = "default"

[params]
disableIcon = true
enableIcon = false

[footer]
since = 2026
customText = ""

[dateFormat]
published = ":date_full"
lastUpdated = ":date_full"

[sidebar]
compact = false
subtitle = "Medical · Life · Tech · Galgame"
avatar = "/img/avatar.jpg"
name = "赛博后花园"

[article]
fullContent = true
headingAnchor = false
math = false
toc = true
readingTime = true
wordCount = true

[article.list]
showTags = false

[article.license]
enabled = true
default = "CC BY-NC-SA 4.0"

[colorScheme]
toggle = true
default = "auto"

[params.home]
fullWidth = true

[widgets]
page = [
    { type = "toc" }
]
homepage = [

    { type = "search" },

    { type = "archives" },

    { type = "categories" },

    { type = "tag-cloud" },

]

[comments]
enabled  = true
provider = "twikoo"

[comments.twikoo]
envId = "https://twikoo.cyberbackgarden.top/"
